name: CI

on: 
  push:
      branches: ["main"]
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v2

      - uses: brian-welsh/composite-build-action/setup@main
        id: setup
        with:
          name: '${{ vars.PRODUCT_NAME }}'

      - name: build
        id: build
        run: |
          $output="$(join-path $(resolve-path '${{ github.workspace }}/../') -childpath 'output')"
          Write-Output "building: ${{ vars.PRODUCT_NAME }} v${{ steps.setup.outputs.informational-version }}"
          write-output "build-output=$output" >> $env:GITHUB_OUTPUT
          
          dotnet build "src/" `
            --configuration release `
            --verbosity minimal `
            -p:TreatWarningsAsErrors=false `
            -p:AnalysisMode=none `
            -p:Copyright="${{ steps.setup.outputs.package-copyright }}" `
            -p:Authors="${{ steps.setup.outputs.package-authors }}" `
            -p:Company="${{ steps.setup.outputs.package-company }}" `
            -p:AssemblyVersion="${{ steps.setup.outputs.version }}" `
            -p:FileVersion="${{ steps.setup.outputs.major-version }}.${{ steps.setup.outputs.build-number }}" `
            -p:InformationalVersion="${{ steps.setup.outputs.informational-version }}+${{ github.sha }}" `
            -p:TrimUnusedDependencies=true `
            -p:IsOnBuildAgent=true `
            -p:CodeAnalysisTreatWarningsAsErrors=false
            # -warnaserror

          Write-Output "Publishing..."
          dotnet publish "src/" `
            --property:PublishDir="$output" `
            --configuration release `
            --no-restore `
            --no-build
        shell: pwsh

      - name: debug
        run: |
            gci env: | select name,value
            Write-host "ref: ${{ github.ref }}"
        shell: pwsh  

      - uses: brian-welsh/composite-build-action/package@main
        id: package
        with:
          package-name: '${{ vars.PRODUCT_NAME }}'
          package-input: "${{ steps.build.outputs.build-output }}"

      - uses: brian-welsh/composite-build-action/release@main
        id: release
        with:
          package-name: '${{ vars.PRODUCT_NAME }}'
          release-version: ${{ steps.setup.outputs.informational-version }}
          release-channel: ${{ steps.setup.outputs.channel }}
          release-package: ${{ steps.package.outputs.path }}          

      - run: |
          write-host 'Version: ${{ steps.setup.outputs.version }}'
          write-host 'Version: ${{ steps.setup.outputs.informational-version }}'
        shell: pwsh





    