name: CI

on: 
  push:
      branches: ["main"]
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       
      - uses: actions/checkout@v3

      - name: debug
        run: |
            gci env: | select name,value
            Write-host "ref: ${{ github.ref }}"
        shell: pwsh  

      - uses: brian-welsh/build-setup-action@dev/v1

      - run: 'gci env: | select name,value'
        shell: pwsh





    