name: CI

on: 
  push:
      branches: ["main"]
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       
      - uses: actions/checkout@v3

      - name: debug
        run: |
            gci env: | select name,value
            Write-host "ref: ${{ github.ref }}"
        shell: pwsh  

      - uses: brian-welsh/composite-build-action/setup@main
        id: setup

      - uses: brian-welsh/composite-build-action/package@main
        id: package
        with:
          package-name: '${{ vars.PRODUCT_NAME }}-${{ steps.setup.outputs.informational-version }}'
 
      - run: |
          write-host 'Version: ${{ steps.setup.outputs.version }}'
          write-host 'Version: ${{ steps.setup.outputs.informational-version }}'
        shell: pwsh





    