name: CI

on: 
  push:
      branches: ["main"]
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v2
      - uses: brian-welsh/build-setup-action@dev/v1

      - run: dotnet build src --configuration release --verbosity minimal

      - run: 'gci env: | select name,value'
        shell: pwsh





    