name: CI

on: 
  push:
      branches: ["build/poc"]

jobs:
  build:
    runs-on: windows-latest

    steps:
       
      - uses: actions/checkout@v3

      - name: debug
        run: |
            gci env: | select name,value
            Write-host "ref: ${{ github.ref }}"
        shell: pwsh  

      - uses: brian-welsh/digital-is-setup-action@main





    