name: CI

on: 
  #push:
  #    branches: ["main"]
      
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
       
      - uses: actions/checkout@v4.1.0

      - uses: actions/setup-dotnet@v3.2.0

      # - uses: wcenterprises/build-action/@main
      # - uses: wcenterprises/build-template-baseline@main
      - uses: wcenterprises/standard-build-actions/actions/setup@daily
        with:
          config-file: .github/action-config/action-config.yml
      
      - uses: wcenterprises/standard-build-actions/actions/package/octopus@daily
      

      - run: |
          echo "debugging"
          printenv | grep '^__*'
        shell: bash
      - run: |
          echo 'more testing'
        shell: bash

    
