name: CI

on: 
  #push:
  #    branches: ["main"]
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       
      - uses: actions/checkout@v4.1.0

      - uses: actions/setup-dotnet@v3.2.0

      - uses: wcenterprises/composite-build-action/setup-action@feature/moderize

      - run: |
          echo "debugging"
          printenv | grep '^__*'
        shell: bash
      - run: |
          echo 'more testing'
        shell: bash

    