name: CI

on: 
  #push:
  #    branches: ["main"]
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       
      - uses: actions/checkout@v4.1.0

      - uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.x

#      - uses: microsoft/setup-msbuild@v1.1
#        with:
#          msbuild-architecture: x64

      - name: dotnet
        if: false
        run: |
          dotnet build src/Bw.PocService.sln --configuration release 
        shell: pwsh

      - name: setup
        uses: wcenterprises/standard-build-actions/actions/setup@daily
        with:
          config-file: .github/action-config/action-config.yml
      
      
      - name: restore
        uses: wcenterprises/standard-build-actions/actions/dotnet@daily
        with:
          command: restore
          projects: '**/*.sln'
        
      - name: build
        if: false
        uses: wcenterprises/standard-build-actions/actions/dotnet@daily
        with:
          command: build
          projects: '**/*.sln'
          configuration: release
          parameters: |
            --no-restore
      - run: 
          /usr/share/dotnet/dotnet build src/Wce.Template.sln --configuration release
        shell: bash
        
      - name: publish
        uses: wcenterprises/standard-build-actions/actions/dotnet@daily
        with:
          command: publish
          projects: '**/*.sln'
          configuration: release
          parameters: |
            --no-restore
            --no-build
        
      - name: pack
        uses: wcenterprises/standard-build-actions/actions/dotnet@daily
        with:
          command: pack
          projects: '**/*.sln'
        
        

      - run: |
          echo "debugging"
          printenv | grep '^__*'
        shell: bash
      - run: |
          echo 'more testing'
        shell: bash

    
