name: CI

on: 
  push:
      branches: ["main"]
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v2

      - name: build
        run: |
          Write-Output "building..."
          dotnet build "src/" `
            --configuration release `
            --verbosity minimal `
            -p:TreatWarningsAsErrors=false `
            -p:AnalysisMode=none

          Write-Output "Publishing..."
          dotnet publish "src/" `
            --output "$(resolve-path '${{ github.workspace }}/../')/output" `
            --configuration release `
            --no-restore `
            --no-build
        shell: pwsh

      - name: debug
        run: |
            gci env: | select name,value
            Write-host "ref: ${{ github.ref }}"
        shell: pwsh  

      - uses: brian-welsh/composite-build-action/setup@main
        id: setup

      - uses: brian-welsh/composite-build-action/package@main
        id: package
        with:
          package-name: '${{ vars.PRODUCT_NAME }}-${{ steps.setup.outputs.informational-version }}'
 
      - run: |
          write-host 'Version: ${{ steps.setup.outputs.version }}'
          write-host 'Version: ${{ steps.setup.outputs.informational-version }}'
        shell: pwsh





    