name: Detect Stale PR and Branches

on: 
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: wcenterprises/standard-build-actions/actions/stale@feature/init-action
        env:
          GH_TOKEN: ${{ github.token }}

