name: ci-test

on: 
  push:
      branches: ["main"]
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       
      - uses: actions/checkout@v3


      - name: build
        id: test
        run: |
          "::notice:: sample"
          write-output "sample=this is me" >> $env:GITHUB_OUTPUT
          $items=gci -recurse -file

          "::notice:: convert to json"
          $arr=$($items.fullname)|convertto-json

          "::notice:: arr"
          $arr

          "::notice::set output"
          write-output "data=$($arr|convertfrom-json)" >> $env:GITHUB_OUTPUT

          "::notice::set env"
          write-output "TEST_DATA=$($arr|convertfrom-json)" >> $env:GITHUB_ENV
        shell: pwsh

      - name: test-var
        run: |

          $items='${{ steps.test.outputs.data }}'

          "${{ steps.test.outputs.sample }}"

          $items

          write-host $items
          
        shell: pwsh


      - name: debug
        if: always()
        run: |
            gci env: | select name,value
            Write-host "ref: ${{ github.ref }}"
        shell: pwsh  

    