name: ci-test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
       
      - uses: actions/checkout@v3


      - name: build
        id: test
        run: |
          "::notice:: sample"
          write-output "sample=this is me" >> $env:GITHUB_OUTPUT
          
          $items=get-item *
          #$items=gci -recurse -file

          "::notice:: convert to json"
          $arr=($($items.fullname)|convertto-json -compress).Replace('\\n','\n')

          "::notice:: arr"
          $arr

          "::notice::set output"
          write-output "data=$($arr)" |Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append

          "::notice::set env"
          write-output "TEST_DATA=$($arr)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: test-var
        run: |

          $items=('${{ steps.test.outputs.data }}'|convertfrom-json)

          $items|%{write-host "::notice::$($_)"}

          # "${{ steps.test.outputs.sample }}"|convertfrom-json

          #$ items

          #write-host $items

          'fromJSON'
          '${{ fromJSON(steps.test.outputs.data) }}'|%{$_}
          
        shell: pwsh


      - name: debug
        if: always()
        run: |
            gci env: | select name,value
            Write-host "ref: ${{ github.ref }}"
        shell: pwsh  

    